// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SortC
NumericVector SortC(NumericVector x);
RcppExport SEXP _StatComp22058_SortC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SortC(x));
    return rcpp_result_gen;
END_RCPP
}
// medianC
double medianC(NumericVector A);
RcppExport SEXP _StatComp22058_medianC(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(medianC(A));
    return rcpp_result_gen;
END_RCPP
}
// bandwidthC
double bandwidthC(NumericMatrix X, int n);
RcppExport SEXP _StatComp22058_bandwidthC(SEXP XSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(bandwidthC(X, n));
    return rcpp_result_gen;
END_RCPP
}
// CorrelationC
NumericMatrix CorrelationC(NumericMatrix X, int N, int v, int w);
RcppExport SEXP _StatComp22058_CorrelationC(SEXP XSEXP, SEXP NSEXP, SEXP vSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(CorrelationC(X, N, v, w));
    return rcpp_result_gen;
END_RCPP
}
// VexpressionC
double VexpressionC(NumericMatrix X, int n, double a, double b);
RcppExport SEXP _StatComp22058_VexpressionC(SEXP XSEXP, SEXP nSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(VexpressionC(X, n, a, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp22058_SortC", (DL_FUNC) &_StatComp22058_SortC, 1},
    {"_StatComp22058_medianC", (DL_FUNC) &_StatComp22058_medianC, 1},
    {"_StatComp22058_bandwidthC", (DL_FUNC) &_StatComp22058_bandwidthC, 2},
    {"_StatComp22058_CorrelationC", (DL_FUNC) &_StatComp22058_CorrelationC, 4},
    {"_StatComp22058_VexpressionC", (DL_FUNC) &_StatComp22058_VexpressionC, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp22058(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
