# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Sort function using Rcpp
#' @description Sort the values in a NumericVector using Rcpp
#' @param x a NumericVector
#' @return a vector contains the values in the NumericVector x sorted from smallest to largest.
#' @examples
#' \dontrun{
#' A <- c(2,1,4,5)
#' SortC(A)
#' }
#' @export
SortC <- function(x) {
    .Call('_StatComp22058_SortC', PACKAGE = 'StatComp22058', x)
}

#' @title Median function using Rcpp
#' @description Compute the median of the values in a NumericVector using Rcpp
#' @param A a NumericVector
#' @return the median of the values in the NumericVector A.
#' @examples
#' \dontrun{
#' A <- c(2,1,4,5)
#' medianC(A)
#' }
#' @export
medianC <- function(A) {
    .Call('_StatComp22058_medianC', PACKAGE = 'StatComp22058', A)
}

#' @title A Function to compute the bandwidth using Rcpp
#' @description Compute the bandwidth using Rcpp. For a time series dataset, the bandwidth is the median Euclidean distance for the data corresponding to all time points.
#' @param X a matrix contains multivariate time series data. The rows are time points and the columns are variables.
#' @param n the number of time points
#' @return the value of bandwidth for the data in X.
#' @examples
#' \dontrun{
#' data(mydata)
#' attach(mydata)
#' N <- length(mydata[,1])
#' h <- bandwidthC(cordata,N)
#' h
#' }
#' @export
bandwidthC <- function(X, n) {
    .Call('_StatComp22058_bandwidthC', PACKAGE = 'StatComp22058', X, n)
}

#' @title Running correlations function using Rcpp
#' @description Compute the running correlations using Rcpp
#' @param X a matrix contains multivariate time series data. The rows are time points and the columns are variables.
#' @param N the number of time points in X
#' @param v the number of variables in X
#' @param w the width of windows. Compute the running correlations in a window.
#' @return a matrix of the running correlations for all variables at these time points.
#' @examples
#' \dontrun{
#' data(mydata)
#' attach(mydata)
#' N <- length(mydata[,1])
#' v <- length(mydata[1,])
#' w <- 15
#' cordata <- CorrelationR(mydata,N,v,w)
#' cordata
#' }
#' @export
CorrelationC <- function(X, N, v, w) {
    .Call('_StatComp22058_CorrelationC', PACKAGE = 'StatComp22058', X, N, v, w)
}

#' @title The within-phase scatter using Rcpp
#' @description Compute the within-phase scatter using Rcpp
#' @param X a matrix contains multivariate time series data. The rows are time points and the columns are variables.
#' @param n the number of time points
#' @param a the last observation in the last phase
#' @param b the last observation in the current phase
#' @return the value of within-phase scatter for the current phase
#' @examples
#' \dontrun{
#' data(mydata)
#' attach(mydata)
#' N <- length(mydata[,1])
#' VC <- VexpressionC(cordata,N,0,N)
#' VC
#' }
#' @export
VexpressionC <- function(X, n, a, b) {
    .Call('_StatComp22058_VexpressionC', PACKAGE = 'StatComp22058', X, n, a, b)
}

